//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CICE_Business_Cycles.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BDINEGI
    {
        public double ID { get; set; }
        public string Raíz { get; set; }
        public string Primer_hijo { get; set; }
        public string Segundo_hijo { get; set; }
        public string Tercer_hijo { get; set; }
        public string Serie { get; set; }
        public string NodoID { get; set; }
        public string Periodo_disponible { get; set; }
        public string Periodicidad { get; set; }
        public string Cifra { get; set; }
        public string Unidad { get; set; }
        public string Tipo_de_información { get; set; }
        public Nullable<double> Serie_ID { get; set; }
        public string F14 { get; set; }
        public string F15 { get; set; }
        public string F16 { get; set; }
        public string F17 { get; set; }
    }
}
