//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CICE_Business_Cycles.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class INEGINodos
    {
        public double ID { get; set; }
        public Nullable<double> Raíz { get; set; }
        public Nullable<double> Primer_hijo { get; set; }
        public Nullable<double> Segundo_hijo { get; set; }
        public Nullable<double> Tercer_hijo { get; set; }
        public Nullable<double> Serie { get; set; }
        public string NodoID { get; set; }
    }
}
