//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMI.ServiceFMI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.imf.org/SDMX", ConfigurationName="ServiceFMI.ISDMXService")]
    public interface ISDMXService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.imf.org/SDMX/ISDMXService/GetCodeList", ReplyAction="http://www.imf.org/SDMX/ISDMXService/GetCodeListResponse")]
        System.Xml.Linq.XElement GetCodeList(System.Xml.Linq.XElement queryMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.imf.org/SDMX/ISDMXService/GetCodeList", ReplyAction="http://www.imf.org/SDMX/ISDMXService/GetCodeListResponse")]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetCodeListAsync(System.Xml.Linq.XElement queryMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.imf.org/SDMX/ISDMXService/GetDataflow", ReplyAction="http://www.imf.org/SDMX/ISDMXService/GetDataflowResponse")]
        System.Xml.Linq.XElement GetDataflow();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.imf.org/SDMX/ISDMXService/GetDataflow", ReplyAction="http://www.imf.org/SDMX/ISDMXService/GetDataflowResponse")]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetDataflowAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.imf.org/SDMX/ISDMXService/GetCompactData", ReplyAction="http://www.imf.org/SDMX/ISDMXService/GetCompactDataResponse")]
        System.Xml.Linq.XElement GetCompactData(System.Xml.Linq.XElement queryMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.imf.org/SDMX/ISDMXService/GetCompactData", ReplyAction="http://www.imf.org/SDMX/ISDMXService/GetCompactDataResponse")]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetCompactDataAsync(System.Xml.Linq.XElement queryMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.imf.org/SDMX/ISDMXService/GetMetadataStructure", ReplyAction="http://www.imf.org/SDMX/ISDMXService/GetMetadataStructureResponse")]
        System.Xml.Linq.XElement GetMetadataStructure(System.Xml.Linq.XElement queryMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.imf.org/SDMX/ISDMXService/GetMetadataStructure", ReplyAction="http://www.imf.org/SDMX/ISDMXService/GetMetadataStructureResponse")]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetMetadataStructureAsync(System.Xml.Linq.XElement queryMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.imf.org/SDMX/ISDMXService/GetGenericMetadata", ReplyAction="http://www.imf.org/SDMX/ISDMXService/GetGenericMetadataResponse")]
        System.Xml.Linq.XElement GetGenericMetadata(System.Xml.Linq.XElement queryMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.imf.org/SDMX/ISDMXService/GetGenericMetadata", ReplyAction="http://www.imf.org/SDMX/ISDMXService/GetGenericMetadataResponse")]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetGenericMetadataAsync(System.Xml.Linq.XElement queryMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.imf.org/SDMX/ISDMXService/GetMaxSeriesInResult", ReplyAction="http://www.imf.org/SDMX/ISDMXService/GetMaxSeriesInResultResponse")]
        int GetMaxSeriesInResult();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.imf.org/SDMX/ISDMXService/GetMaxSeriesInResult", ReplyAction="http://www.imf.org/SDMX/ISDMXService/GetMaxSeriesInResultResponse")]
        System.Threading.Tasks.Task<int> GetMaxSeriesInResultAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.imf.org/SDMX/ISDMXService/GetDataStructure", ReplyAction="http://www.imf.org/SDMX/ISDMXService/GetDataStructureResponse")]
        System.Xml.Linq.XElement GetDataStructure(System.Xml.Linq.XElement queryMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.imf.org/SDMX/ISDMXService/GetDataStructure", ReplyAction="http://www.imf.org/SDMX/ISDMXService/GetDataStructureResponse")]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetDataStructureAsync(System.Xml.Linq.XElement queryMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.imf.org/SDMX/ISDMXService/GetServiceVersion", ReplyAction="http://www.imf.org/SDMX/ISDMXService/GetServiceVersionResponse")]
        string GetServiceVersion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.imf.org/SDMX/ISDMXService/GetServiceVersion", ReplyAction="http://www.imf.org/SDMX/ISDMXService/GetServiceVersionResponse")]
        System.Threading.Tasks.Task<string> GetServiceVersionAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISDMXServiceChannel : FMI.ServiceFMI.ISDMXService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SDMXServiceClient : System.ServiceModel.ClientBase<FMI.ServiceFMI.ISDMXService>, FMI.ServiceFMI.ISDMXService {
        
        public SDMXServiceClient() {
        }
        
        public SDMXServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SDMXServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SDMXServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SDMXServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Xml.Linq.XElement GetCodeList(System.Xml.Linq.XElement queryMessage) {
            return base.Channel.GetCodeList(queryMessage);
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetCodeListAsync(System.Xml.Linq.XElement queryMessage) {
            return base.Channel.GetCodeListAsync(queryMessage);
        }
        
        public System.Xml.Linq.XElement GetDataflow() {
            return base.Channel.GetDataflow();
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetDataflowAsync() {
            return base.Channel.GetDataflowAsync();
        }
        
        public System.Xml.Linq.XElement GetCompactData(System.Xml.Linq.XElement queryMessage) {
            return base.Channel.GetCompactData(queryMessage);
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetCompactDataAsync(System.Xml.Linq.XElement queryMessage) {
            return base.Channel.GetCompactDataAsync(queryMessage);
        }
        
        public System.Xml.Linq.XElement GetMetadataStructure(System.Xml.Linq.XElement queryMessage) {
            return base.Channel.GetMetadataStructure(queryMessage);
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetMetadataStructureAsync(System.Xml.Linq.XElement queryMessage) {
            return base.Channel.GetMetadataStructureAsync(queryMessage);
        }
        
        public System.Xml.Linq.XElement GetGenericMetadata(System.Xml.Linq.XElement queryMessage) {
            return base.Channel.GetGenericMetadata(queryMessage);
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetGenericMetadataAsync(System.Xml.Linq.XElement queryMessage) {
            return base.Channel.GetGenericMetadataAsync(queryMessage);
        }
        
        public int GetMaxSeriesInResult() {
            return base.Channel.GetMaxSeriesInResult();
        }
        
        public System.Threading.Tasks.Task<int> GetMaxSeriesInResultAsync() {
            return base.Channel.GetMaxSeriesInResultAsync();
        }
        
        public System.Xml.Linq.XElement GetDataStructure(System.Xml.Linq.XElement queryMessage) {
            return base.Channel.GetDataStructure(queryMessage);
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetDataStructureAsync(System.Xml.Linq.XElement queryMessage) {
            return base.Channel.GetDataStructureAsync(queryMessage);
        }
        
        public string GetServiceVersion() {
            return base.Channel.GetServiceVersion();
        }
        
        public System.Threading.Tasks.Task<string> GetServiceVersionAsync() {
            return base.Channel.GetServiceVersionAsync();
        }
    }
}
